import { Product } from './types';

// Product data store
export const productsData: Record<string, Product> = {
  'pants-1': {
    id: 'pants-1',
    name: 'Брюки Союз 2.0',
    price: '5000 ₽',
    image: '/assets/DSC09365.jpg',
    images: [
      '/assets/items/17.jpg',
      '/assets/items/18.jpg',
      '/assets/items/DSC00576.jpg',
      '/assets/items/DSC00578.jpg',
      '/assets/items/DSC00583.jpg',
      '/assets/items/DSC09246.jpg',
      '/assets/items/DSC09266.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Брюки из плотного хлопка с вышивкой логотипа СОЮЗ. Свободный крой, удобные карманы и эластичный пояс.',
      eng: 'Pants made of thick cotton with СОЮЗ logo embroidery. Relaxed fit, comfortable pockets and elastic waistband.',
    },
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
  },
  'hoodie-1': {
    id: 'hoodie-1',
    name: 'Худи Союз',
    price: '5000 ₽',
    image: '/assets/DSC09470.jpg',
    images: [
      '/assets/DSC09470.jpg',
      '/assets/items/DSC09444.jpg',
      '/assets/items/DSC09428.jpg',
      '/assets/items/DSC09471.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Худи из мягкого хлопка с вышивкой логотипа СОЮЗ. Свободный крой и удобный капюшон.',
      eng: 'Hoodie made of soft cotton with СОЮЗ logo embroidery. Relaxed fit and comfortable hood.',
    },
    sizes: ['S', 'M', 'L', 'XL'],
  },
  'tshirt-daktil': {
    id: 'tshirt-daktil',
    name: 'Футболка Дактиль',
    price: '2500 ₽',
    image: '/assets/shop/daktil.jpg',
    images: [
      '/assets/items/1.jpg',
      '/assets/items/2.jpg',
      '/assets/items/DSC00703.jpg',
      '/assets/items/DSC00707.jpg',
      '/assets/items/DSC00709.jpg',
      '/assets/shop/daktil.jpg',
      '/assets/items/DSC05560.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Футболка из 100% хлопка с авторским принтом.',
      eng: '100% cotton t-shirt with original print.',
    },
    sizes: ['S', 'M', 'L', 'XL'],
  },
  'tshirt-skulls': {
    id: 'tshirt-skulls',
    name: 'Футболка Черепа',
    price: '2500 ₽',
    image: '/assets/shop/SKEKETDUO.jpg',
    images: [
      '/assets/items/13.jpg',
      '/assets/items/14.jpg',
      '/assets/items/DSC00694.jpg',
      '/assets/items/DSC00696.jpg',
      '/assets/items/DSC00698.jpg',
      '/assets/items/DSC00701.jpg',
      '/assets/shop/SKEKETDUO.jpg',
      '/assets/items/DSC04288.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Футболка из 100% хлопка с авторским принтом.',
      eng: '100% cotton t-shirt with original print.',
    },
    sizes: ['L', 'XL', 'XXL'],
  },
  'tshirt-tennis': {
    id: 'tshirt-tennis',
    name: 'Футболка Теннис',
    price: '2500 ₽',
    image: '/assets/shop/ponger.jpg',
    images: [
      '/assets/items/15.jpg',
      '/assets/items/16.jpg',
      '/assets/shop/ponger.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Футболка из 100% хлопка с авторским принтом.',
      eng: '100% cotton t-shirt with original print.',
    },
    sizes: ['M', 'XL'],
  },
  'tshirt-okrug': {
    id: 'tshirt-okrug',
    name: 'Футболка Округ',
    price: '3000 ₽',
    image: '/assets/shop/okrug.jpg',
    images: ['/assets/shop/okrug.jpg'],
    category: 'friends',
    brand: 'Округ',
    description: {
      rus: 'Коллаборация с брендом Округ. Лимитированная серия.',
      eng: 'Collaboration with Округ brand. Limited edition.',
    },
    sizes: ['XXL'],
  },
  'long-pink': {
    id: 'long-pink',
    name: 'Лонгслив Огонь розовый',
    price: '3500 ₽',
    image: '/assets/shop/flamelong.jpg',
    images: ['/assets/shop/flamelong.jpg'],
    category: 'clothing',
    description: {
      rus: 'Лонгслив из мягкого хлопка с авторским принтом.',
      eng: 'Soft cotton longsleeve with original print.',
    },
    sizes: ['L', 'XL'],
  },
  'crop-cherry': {
    id: 'crop-cherry',
    name: 'Кроп Вишни',
    price: '2000 ₽',
    image: '/assets/shop/topcherry.jpg',
    images: [
      '/assets/items/9.jpg',
      '/assets/items/10.jpg',
      '/assets/items/DSC00670.jpg',
      '/assets/items/DSC00673.jpg',
      '/assets/shop/topcherry.jpg',
      '/assets/items/DSC04029.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Стильный кроп-топ с принтом вишни.',
      eng: 'Stylish crop top with cherry print.',
    },
    sizes: ['XS', 'S', 'M'],
  },
  'crop-tie': {
    id: 'crop-tie',
    name: 'Кроп Бант',
    price: '2000 ₽',
    image: '/assets/shop/topBANTIK.jpg',
    images: [
      '/assets/items/11.jpg',
      '/assets/items/12.jpg',
      '/assets/items/DSC00677.jpg',
      '/assets/items/DSC00683.jpg',
      '/assets/items/DSC00683.jpg',
      '/assets/items/DSC03876.jpg',
      '/assets/items/DSC03917.jpg',
      '/assets/items/DSC03934.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Стильный кроп-топ с декоративным бантом.',
      eng: 'Stylish crop top with decorative bow.',
    },
    sizes: ['XS', 'S', 'M'],
  },
  'crop-black': {
    id: 'crop-black',
    name: 'Кроп черный',
    price: '2000 ₽',
    image: '/assets/shop/toppinkFRONT.jpg',
    images: [
      '/assets/items/7.jpg',
      '/assets/items/8.jpg',
      '/assets/items/DSC00684.jpg',
      '/assets/items/DSC00688.jpg',
      '/assets/shop/toppinkFRONT.jpg',
      '/assets/items/DSC04057.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Стильный черный кроп-топ с минималистичным дизайном.',
      eng: 'Stylish black crop top with minimalist design.',
    },
    sizes: ['XS', 'S', 'M'],
  },
  bucketbag: {
    id: 'bucketbag',
    name: 'Сумка bucket',
    price: '2500 ₽',
    image: '/assets/items/DSC00641.jpg',
    images: [
      '/assets/items/DSC00641.jpg',
      '/assets/items/DSC00644.jpg',
      '/assets/items/DSC00645.jpg',
      '/assets/items/DSC00646.jpg',
      '/assets/items/DSC00649.jpg',
      '/assets/items/DSC00650.jpg',
      '/assets/items/DSC00651.jpg',
      '/assets/items/DSC00653.jpg',
    ],
    category: 'accessories',
    description: {
      rus: 'Вместительная сумка в стиле bucket bag с логотипом СОЮЗ.',
      eng: 'Spacious bucket bag with СОЮЗ logo.',
    },
    sizes: ['Один размер'],
  },
  case: {
    id: 'case',
    name: 'Чехол для очков',
    price: '1000 ₽',
    image: '/assets/items/DSC00612.jpg',
    images: [
      '/assets/items/DSC00612.jpg',
      '/assets/items/DSC00614.jpg',
      '/assets/items/DSC00620.jpg',
      '/assets/items/DSC00623.jpg',
      '/assets/items/DSC04548.jpg',
      '/assets/shop/bagf.jpg',
    ],
    category: 'accessories',
    description: {
      rus: 'Защитный чехол для очков с логотипом СОЮЗ.',
      eng: 'Protective glasses case with СОЮЗ logo.',
    },
    sizes: ['Один размер'],
  },
  'longsleeve-spring': {
    id: 'longsleeve-spring',
    name: 'Лонгсливы весенние',
    price: 'Цена по запросу',
    image: '/assets/items/DSC00997-Улучшено-Ум. шума.jpg',
    images: [
      '/assets/items/DSC00997-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC00968-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC01105-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC01150-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC01159-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC01161-Улучшено-Ум. шума.jpg',
      '/assets/items/DSC01202-Улучшено-Ум. шума.jpg',
    ],
    category: 'clothing',
    description: {
      rus: 'Лёгкий весенний лонгслив из хлопка.',
      eng: 'Lightweight spring cotton longsleeve.',
    },
    sizes: ['S', 'M', 'L', 'XL'],
  },
  socks: {
    id: 'socks',
    name: 'Носки',
    price: 'Цена по запросу',
    image: '/assets/items/DSC00591.jpg',
    images: [
      '/assets/items/DSC00591.jpg',
      '/assets/items/DSC00593.jpg',
      '/assets/items/DSC00594.jpg',
      '/assets/items/DSC09502.jpg',
    ],
    category: 'accessories',
    description: {
      rus: 'Удобные носки с вышивкой логотипа.',
      eng: 'Comfortable socks with logo embroidery.',
    },
    sizes: [],
  },
  'bag-cow': {
    id: 'bag-cow',
    name: 'Сумка-коровка',
    price: 'Цена по запросу',
    image: '/assets/items/korovka.jpg',
    images: [
      '/assets/items/korovka.jpg',
      '/assets/items/DSC00600.jpg',
      '/assets/items/DSC00601.jpg',
      '/assets/items/DSC00602.jpg',
      '/assets/items/DSC00603.jpg',
      '/assets/items/DSC00604.jpg',
    ],
    category: 'accessories',
    description: {
      rus: 'Лёгкая хлопковая сумка с принтом.',
      eng: 'Lightweight cotton bag with print.',
    },
    sizes: [],
  },
};

// --- Функции ниже оставить без изменений ---
export function getProductsByCategory(category: string) {
  return Object.values(productsData).filter(
    (product) => product.category === category
  );
}

export function getAllProducts() {
  return Object.values(productsData);
}
